name: "Push to Cachix"
on:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v11
      with:
        name: haskell-tools
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: for ghcVersion in ghc94 ghc92 ghc90; do mkdir -p result/nixpkgs/$ghcVersion; nix-store -qR --include-outputs $(nix-instantiate --argstr compiler $ghcVersion demo.nix --add-root result/nixpkgs/$fgcVersion --indirect) | cachix push haskell-tools; done
